name: 'SIGMA Analysis'
description: 'Analyze a repository using the SIGMA analysis engine.'
outputs:
    results:
        description: 'File containing the results'
runs:
    using: 'docker'
    image: 'Dockerfile'

